
#Default Server Settings
[general]
	#The default list of slab types and variants to ignore when creating double slabs for use when the server config generates
	#Example: minecraft:purpur_slab
	default_slab_blacklist = []
	#Whether to use the custom double slab when combining slabs of the same type
	default_replace_same_slab = true
	#Whether to disable the placement of vertical slabs from regular horizontal slabs when holding shift
	default_disable_vertical_slab_placement = false
	#Whether to use an alternate system when placing vertical slabs
	default_alternate_vertical_slab_placement = true

